version: '3'

services:
  ansible:
    build:
      ./ansible
    volumes:
      - ./Azdo-Modular-Infrastructure-Pipelines/:/home/ansible/SolutionThree
      - ~/.ssh:/home/ansible/.ssh
      - ~/.gitconfig:/home/ansible/.gitconfig
    stdin_open: true
    tty: true
    command: tail -f /dev/null
